package ru.cinimex.learn;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.1.5.redhat-630254
 * 2017-06-09T18:33:02.854+03:00
 * Generated source version: 3.1.5.redhat-630254
 * 
 */
@WebService(targetNamespace = "http://ru.cinimex.learn.cinimex.ru/", name = "phonebookWS")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface PhonebookWS {

    @WebMethod(action = "getPhineByFIO")
    @WebResult(name = "phone", targetNamespace = "http://ru.cinimex.learn.cinimex.ru/", partName = "phone")
    public int getPhineByFIO(
        @WebParam(partName = "lastName", name = "lastName")
        java.lang.String lastName,
        @WebParam(partName = "firstName", name = "firstName")
        java.lang.String firstName,
        @WebParam(partName = "middleName", name = "middleName")
        java.lang.String middleName
    );
}
