package ru.cinimex.learn;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.5.redhat-630254
 * 2017-06-09T18:33:02.884+03:00
 * Generated source version: 3.1.5.redhat-630254
 * 
 */
@WebServiceClient(name = "phonebookWS_Client", 
                  wsdlLocation = "file:/C:/Users/efischenko/Desktop/efischenko-learning/project2/phonebookWs/src/main/resources/wsdl/phonebook.wsdl",
                  targetNamespace = "http://ru.cinimex.learn.cinimex.ru/")
public class PhonebookWSClient extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ru.cinimex.learn.cinimex.ru/", "phonebookWS_Client");
    public final static QName Namechegoto = new QName("http://ru.cinimex.learn.cinimex.ru/", "Namechegoto");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/efischenko/Desktop/efischenko-learning/project2/phonebookWs/src/main/resources/wsdl/phonebook.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PhonebookWSClient.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/efischenko/Desktop/efischenko-learning/project2/phonebookWs/src/main/resources/wsdl/phonebook.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PhonebookWSClient(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PhonebookWSClient(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PhonebookWSClient() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public PhonebookWSClient(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PhonebookWSClient(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PhonebookWSClient(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns PhonebookWS
     */
    @WebEndpoint(name = "Namechegoto")
    public PhonebookWS getNamechegoto() {
        return super.getPort(Namechegoto, PhonebookWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PhonebookWS
     */
    @WebEndpoint(name = "Namechegoto")
    public PhonebookWS getNamechegoto(WebServiceFeature... features) {
        return super.getPort(Namechegoto, PhonebookWS.class, features);
    }

}
