package ru.cinimex.learn.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.5.redhat-630254
 * 2017-06-09T16:20:03.229+03:00
 * Generated source version: 3.1.5.redhat-630254
 * 
 */
@WebService(targetNamespace = "http://learn.cinimex.ru/service", name = "customerWS")
@XmlSeeAlso({ru.cinimex.learn.customer.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CustomerWS {

    @WebMethod
    @WebResult(name = "customer", targetNamespace = "", partName = "customer")
    public ru.cinimex.learn.customer.CustomerBDlist getCustomerByPhone(
            @WebParam(partName = "Phone", name = "Phone", targetNamespace = "")
                    ru.cinimex.learn.customer.PhoneList phone
    );

    @WebMethod
    @WebResult(name = "customer", targetNamespace = "", partName = "customer")
    public ru.cinimex.learn.customer.Customers createCustomer(
            @WebParam(partName = "Date_for_Customer", name = "Date_for_Customer", targetNamespace = "")
                    ru.cinimex.learn.customer.Customers dateForCustomer
    );
}
