<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions  name="MyFirstWSDL" targetNamespace="http://task.cinimex.ru/service"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://task.cinimex.ru/service"
    xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">



    <message name="Request">
        <part name="person" type="xsd:string"></part>
    </message>

    <message name="Response">
        <part name="greeting" type="xsd:string"></part>
    </message>

    <portType name="HelloWorld">
        <operation name="sayHi">
            <input message="tns:Request"></input>
            <output message="tns:Response"></output>
        </operation>
    </portType>

    <binding name="Name_Binding" type="tns:HelloWorld">
        <soap:binding style="document"
            transport="http://schemas.xmlsoap.org/soap/http" />
        <operation name="sayHi">
            <input>
                <soap:body use="literal" />
            </input>
            <output>
                <soap:body use="literal" />
            </output>
        </operation>
    </binding>

    <service name="HelloWorld_ServiceClient">
        <port name="HelloWorld_Port" binding="tns:Name_Binding">
            <soap:address
                location="http://localhost:8083/helloworld" />
        </port>
    </service>
</definitions>